In [25]:
#1.	Write a Python Program to Add Two Matrices?
import numpy as np
m1 = np.random.randint(1,10,size=(3,4))
m2 = np.random.randint(11,20,size=(3,4))
print('Matrix 1:\n',m1)
print('Matrix 2:\n',m2)
print('Sum of the 2 matrices:\n',m1+m2)

Matrix 1:
 [[8 3 1 7]
 [6 5 6 8]
 [3 1 6 1]]
Matrix 2:
 [[11 17 13 15]
 [18 19 14 13]
 [12 17 14 16]]
Sum of the 2 matrices:
 [[19 20 14 22]
 [24 24 20 21]
 [15 18 20 17]]


In [26]:
#2.	Write a Python Program to Multiply Two Matrices?
import numpy as np
m1 = np.random.randint(1,10,size=(3,4))
m2 = np.random.randint(11,20,size=(4,3))
print('Matrix 1:\n',m1)
print('Matrix 2:\n',m2)
print('Product of the 2 matrices:\n',np.matmul(m1,m2))

Matrix 1:
 [[1 8 6 4]
 [8 4 1 8]
 [1 9 5 1]]
Matrix 2:
 [[11 16 13]
 [11 13 15]
 [15 19 15]
 [19 11 18]]
Product of the 2 matrices:
 [[265 278 295]
 [299 287 323]
 [204 239 241]]


In [27]:
#3.	Write a Python Program to Transpose a Matrix?
import numpy as np
m1 = np.random.randint(1,10,size=(3,4))
print('Matrix:\n',m1)
print('Transposed matrix:\n',m1.T)

Matrix:
 [[4 1 9 4]
 [5 6 6 3]
 [4 8 3 6]]
Transposed matrix:
 [[4 5 4]
 [1 6 8]
 [9 6 3]
 [4 3 6]]


In [31]:
#4.	Write a Python Program to Sort Words in Alphabetic Order?
words = ['Zebra','Apple','Alpha@123','Ball','Yatch','Tree','Cat']
print('Original list: ',words)
words.sort()
print('Sorted list: ',words)

Original list:  ['Zebra', 'Apple', 'Alpha@123', 'Ball', 'Yatch', 'Tree', 'Cat']
Sorted list:  ['Alpha@123', 'Apple', 'Ball', 'Cat', 'Tree', 'Yatch', 'Zebra']


In [32]:
#5.	Write a Python Program to Remove Punctuation From a String?
string = "While he [Mr. Smith] was writing his book, Magic: the little known world! he stated, \"I always… wanted to ask a magician, 'How do you do it?''\"; he luckily got the chance while he was living above a math-based magic shop (where he lived from 1993 — 1997) called 2{1+[23-3]}=x."

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

# remove punctuation from the string
no_punct = ""
for char in string:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

While he Mr Smith was writing his book Magic the little known world he stated I always… wanted to ask a magician How do you do it he luckily got the chance while he was living above a mathbased magic shop where he lived from 1993 — 1997 called 21+233=x
